### PR TITLE
add tutorial for billiards

### PR DESCRIPTION
**Pull request by Datseris**

### CODE REVIEW

**Comment by crstnbr** [comment]
Thanks for the PR! Would it make sense to move your other tutorial into the "Dynamical Systems" category as well?

**Comment by Datseris** [comment]
Hey @crstnbr , you are welcome. Sorry, which tutorial are you referring to?

**Comment by crstnbr** [comment]
The "How to easily code a billiard taking advantage of Julia's multiple dispatch" one which you've added a couple of days ago. (check the same file)

**Comment by Datseris** [comment]
lol I forgot about this.... :P Better to have a dynamical systems section, I'll be adding more there.

**Comment by crstnbr** [comment]
Would be great to have more JuliaDynamics stuff! Maybe a simple "usage" example showing off some features would be great.

**Pull request merged**
